######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 11 12:23:03 2012
######################################################################

TEMPLATE = app
TARGET = primon
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += display_manager.h primon.h
SOURCES += display_manager.cpp main.cpp primon.cpp
